from __future__ import annotations

from pathlib import Path


OUTPUT_ROOT = Path("出力")

EXTRACT_TARGET_TIMESERIES_OUTPUT_DIR = OUTPUT_ROOT / "01_時系列抽出"
EXTRACT_TARGET_TIMESERIES_CSV_DIR = EXTRACT_TARGET_TIMESERIES_OUTPUT_DIR / "CSV" / "時系列"
EXTRACT_TARGET_TIMESERIES_ATTITUDE_FIGURE_DIR = EXTRACT_TARGET_TIMESERIES_OUTPUT_DIR / "画像" / "姿勢角時系列"

ANALYZE_TURN_TREND_OUTPUT_DIR = OUTPUT_ROOT / "02_旋回傾向解析"
ANALYZE_TURN_TREND_ALIGNED_CSV_DIR = ANALYZE_TURN_TREND_OUTPUT_DIR / "CSV" / "整列サンプル"
ANALYZE_TURN_TREND_SUMMARY_CSV_DIR = ANALYZE_TURN_TREND_OUTPUT_DIR / "CSV" / "全体要約"
ANALYZE_TURN_TREND_SEGMENT_CSV_DIR = ANALYZE_TURN_TREND_OUTPUT_DIR / "CSV" / "レバー一定区間"
ANALYZE_TURN_TREND_DECAY_CSV_DIR = ANALYZE_TURN_TREND_OUTPUT_DIR / "CSV" / "減衰解析"
ANALYZE_TURN_TREND_RELATIONSHIP_FIGURE_DIR = ANALYZE_TURN_TREND_OUTPUT_DIR / "画像" / "姿勢影響"
ANALYZE_TURN_TREND_SUMMARY_FIGURE_DIR = ANALYZE_TURN_TREND_OUTPUT_DIR / "画像" / "レバー要約"
ANALYZE_TURN_TREND_SURFACE_FIGURE_DIR = ANALYZE_TURN_TREND_OUTPUT_DIR / "画像" / "3D分布"
ANALYZE_TURN_TREND_DECAY_FIGURE_DIR = ANALYZE_TURN_TREND_OUTPUT_DIR / "画像" / "減衰解析"

COMPARE_ROLL_PITCH_YAW_3D_OUTPUT_DIR = OUTPUT_ROOT / "03_3D比較"
COMPARE_ROLL_PITCH_YAW_3D_FIGURE_DIR = COMPARE_ROLL_PITCH_YAW_3D_OUTPUT_DIR / "画像" / "3D比較"

BUILD_STATIC_ZERO_TILT_MODEL_OUTPUT_DIR = OUTPUT_ROOT / "04_静的ゼロ傾きモデル"
BUILD_STATIC_ZERO_TILT_MODEL_MAP_CSV_DIR = BUILD_STATIC_ZERO_TILT_MODEL_OUTPUT_DIR / "CSV" / "静的マップ"
BUILD_STATIC_ZERO_TILT_MODEL_MODEL_CSV_DIR = BUILD_STATIC_ZERO_TILT_MODEL_OUTPUT_DIR / "CSV" / "静的モデル"
BUILD_STATIC_ZERO_TILT_MODEL_FIGURE_DIR = BUILD_STATIC_ZERO_TILT_MODEL_OUTPUT_DIR / "画像" / "静的モデル"

BUILD_GENERALIZED_TURN_MODEL_OUTPUT_DIR = OUTPUT_ROOT / "05_汎用旋回モデル"
BUILD_GENERALIZED_TURN_MODEL_TRAINING_CSV_DIR = BUILD_GENERALIZED_TURN_MODEL_OUTPUT_DIR / "CSV" / "学習データ"
BUILD_GENERALIZED_TURN_MODEL_COEFFICIENTS_CSV_DIR = BUILD_GENERALIZED_TURN_MODEL_OUTPUT_DIR / "CSV" / "モデル係数"
BUILD_GENERALIZED_TURN_MODEL_GRID_CSV_DIR = BUILD_GENERALIZED_TURN_MODEL_OUTPUT_DIR / "CSV" / "モデルグリッド"
BUILD_GENERALIZED_TURN_MODEL_PREDICTIONS_CSV_DIR = BUILD_GENERALIZED_TURN_MODEL_OUTPUT_DIR / "CSV" / "予測結果"
BUILD_GENERALIZED_TURN_MODEL_VALIDATION_CSV_DIR = BUILD_GENERALIZED_TURN_MODEL_OUTPUT_DIR / "CSV" / "検証"
BUILD_GENERALIZED_TURN_MODEL_ADDED_DATA_COMPARISON_CSV_DIR = BUILD_GENERALIZED_TURN_MODEL_OUTPUT_DIR / "CSV" / "追加データ比較"
BUILD_GENERALIZED_TURN_MODEL_OVERVIEW_FIGURE_DIR = BUILD_GENERALIZED_TURN_MODEL_OUTPUT_DIR / "画像" / "モデル概要"
BUILD_GENERALIZED_TURN_MODEL_VALIDATION_FIGURE_DIR = BUILD_GENERALIZED_TURN_MODEL_OUTPUT_DIR / "画像" / "検証"
BUILD_GENERALIZED_TURN_MODEL_MOMENT_FIGURE_DIR = BUILD_GENERALIZED_TURN_MODEL_OUTPUT_DIR / "画像" / "モーメント影響"
BUILD_GENERALIZED_TURN_MODEL_ADDED_DATA_COMPARISON_FIGURE_DIR = BUILD_GENERALIZED_TURN_MODEL_OUTPUT_DIR / "画像" / "追加データ比較"

TURN_MPC_STATIC_DEMO_OUTPUT_DIR = OUTPUT_ROOT / "06_MPC静的デモ"

VALIDATE_TURN_MPC_CASES_OUTPUT_DIR = OUTPUT_ROOT / "07_MPCケース検証"
VALIDATE_TURN_MPC_CASES_SUMMARY_CSV_DIR = VALIDATE_TURN_MPC_CASES_OUTPUT_DIR / "CSV" / "総合検証"
VALIDATE_TURN_MPC_CASES_CASES_DIR = VALIDATE_TURN_MPC_CASES_OUTPUT_DIR / "ケース別"

TURN_MODEL_COEFFICIENTS_CSV = BUILD_GENERALIZED_TURN_MODEL_COEFFICIENTS_CSV_DIR / "turn_model_coefficients.csv"


def ensure_output_dir(output_dir: Path) -> Path:
    output_dir.mkdir(parents=True, exist_ok=True)
    return output_dir


def ensure_parent_dir(path: Path) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    return path


def resolve_prefixed_output(output_prefix: str | Path, output_dir: Path) -> str:
    prefix_path = Path(output_prefix)
    if prefix_path.is_absolute() or prefix_path.parent != Path("."):
        return str(prefix_path)
    return str(output_dir / prefix_path)